leftnav:
- identifier: 122ae65e-9a00-a619-77b2-22f1043987af
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 669dc27e-1a98-591a-d550-47faea6ed2b7
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: d1505680-ea8f-62af-d6b1-2518830092ee
  name: Assignments
  url: /pages/assignments
  weight: 30
- identifier: a4c4c5a4-f7e6-46c5-8700-85ac6d63a818
  name: Quiz
  url: /pages/quiz
  weight: 40
